#mybatis
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.ys.idartix.db.domain


#分页配置
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
  returnPageInfo: check